/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Frognas
 */
public class AñadirCuenta extends javax.swing.JFrame {

    /**
     * Creates new form AñadirCuenta
     */
    public AñadirCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
       return retValue;
   } 
    public void limpiarCampos(){
        jTextFieldNombreCuenta.setText("");
        jTextFieldSaldoInicial.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSaldo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTipoCuenta = new javax.swing.JLabel();
        jLabelGuardar = new javax.swing.JLabel();
        jLabelCancelar = new javax.swing.JLabel();
        jTextFieldSaldoInicial = new javax.swing.JTextField();
        jTextFieldNombreCuenta = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Saldo.png"))); // NOI18N
        getContentPane().add(jLabelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));

        jLabelNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NombreLapiz.png"))); // NOI18N
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 153, -1, -1));

        jLabelTipoCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuentasBlanco.png"))); // NOI18N
        getContentPane().add(jLabelTipoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabelGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonGuardar1.png"))); // NOI18N
        getContentPane().add(jLabelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, -1, -1));

        jLabelCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCancelar1.png"))); // NOI18N
        jLabelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, -1, -1));

        jTextFieldSaldoInicial.setBackground(new java.awt.Color(0, 28, 75));
        jTextFieldSaldoInicial.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldSaldoInicial.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSaldoInicial.setText("$Saldo Inicial...");
        jTextFieldSaldoInicial.setBorder(null);
        jTextFieldSaldoInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSaldoInicialMouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldSaldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 330, 30));

        jTextFieldNombreCuenta.setBackground(new java.awt.Color(0, 28, 75));
        jTextFieldNombreCuenta.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldNombreCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreCuenta.setText("Nombre Cuenta...");
        jTextFieldNombreCuenta.setBorder(null);
        jTextFieldNombreCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNombreCuentaMouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 320, 30));

        jComboBox1.setBackground(new java.awt.Color(0, 28, 75));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 330, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirCuentaInterfaz.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarMouseClicked
        // TODO add your handling code here:
         
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCancelarMouseClicked

    private void jTextFieldNombreCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreCuentaMouseClicked
        // TODO add your handling code here:
        jTextFieldNombreCuenta.setText("");
    }//GEN-LAST:event_jTextFieldNombreCuentaMouseClicked

    private void jTextFieldSaldoInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSaldoInicialMouseClicked
        // TODO add your handling code here:
        jTextFieldSaldoInicial.setText("");
    }//GEN-LAST:event_jTextFieldSaldoInicialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelCancelar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelTipoCuenta;
    private javax.swing.JTextField jTextFieldNombreCuenta;
    private javax.swing.JTextField jTextFieldSaldoInicial;
    // End of variables declaration//GEN-END:variables
}
