/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Frognas
 */
public class AñadirTransferencia extends javax.swing.JFrame {

    /**
     * Creates new form AñadirCuenta
     */
    public AñadirTransferencia() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
       return retValue;
   } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelValor = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelCuentaDestino = new javax.swing.JLabel();
        jLabelGuardar = new javax.swing.JLabel();
        jLabelCancelar = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jComboBoxCuenta = new javax.swing.JComboBox<>();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelCuentaOrigen = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Saldo.png"))); // NOI18N
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, -1, -1));

        jLabelFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoFecha.png"))); // NOI18N
        getContentPane().add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 345, -1, -1));

        jLabelCuentaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuentasBlanco.png"))); // NOI18N
        getContentPane().add(jLabelCuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));

        jLabelGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonGuardar1.png"))); // NOI18N
        getContentPane().add(jLabelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, -1, -1));

        jLabelCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCancelar1.png"))); // NOI18N
        jLabelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, -1, -1));

        jTextFieldValor.setBackground(new java.awt.Color(0, 28, 75));
        jTextFieldValor.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldValor.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldValor.setText("$Valor...");
        jTextFieldValor.setBorder(null);
        jTextFieldValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldValorMouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 330, 30));

        jTextFieldFecha.setBackground(new java.awt.Color(0, 28, 75));
        jTextFieldFecha.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldFecha.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldFecha.setText("Fecha...");
        jTextFieldFecha.setBorder(null);
        jTextFieldFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldFechaMouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 320, 30));

        jComboBoxCuenta.setBackground(new java.awt.Color(0, 28, 75));
        jComboBoxCuenta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 330, 30));

        jLabelDescripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NombreLapiz.png"))); // NOI18N
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 433, -1, -1));

        jLabelCuentaOrigen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuentasBlanco.png"))); // NOI18N
        getContentPane().add(jLabelCuentaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 205, -1, -1));

        jComboBoxCategoria.setBackground(new java.awt.Color(0, 28, 75));
        jComboBoxCategoria.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 330, 30));

        jTextFieldDescripcion.setBackground(new java.awt.Color(0, 28, 75));
        jTextFieldDescripcion.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDescripcion.setText("Descripcion...");
        jTextFieldDescripcion.setBorder(null);
        jTextFieldDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDescripcionMouseClicked(evt);
            }
        });
        jTextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 320, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirIngresosInterfaz.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarMouseClicked
        // TODO add your handling code here:
         
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCancelarMouseClicked

    private void jTextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionActionPerformed

    private void jTextFieldValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldValorMouseClicked
        // TODO add your handling code here:
        jTextFieldValor.setText("");
    }//GEN-LAST:event_jTextFieldValorMouseClicked

    private void jTextFieldDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionMouseClicked
        // TODO add your handling code here:
        jTextFieldDescripcion.setText("");
    }//GEN-LAST:event_jTextFieldDescripcionMouseClicked

    private void jTextFieldFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFechaMouseClicked
        // TODO add your handling code here:
        jTextFieldFecha.setText("");
    }//GEN-LAST:event_jTextFieldFechaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirTransferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxCuenta;
    private javax.swing.JLabel jLabelCancelar;
    private javax.swing.JLabel jLabelCuentaDestino;
    private javax.swing.JLabel jLabelCuentaOrigen;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
