/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import entidades.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Frognas
 */
public class MenuMovimientos extends javax.swing.JFrame {
    
    private Usuario user;
    /**
     * Creates new form MenuCuentas
     * @param user
     */
    public MenuMovimientos(Usuario user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
    }

     public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo2.png"));
       return retValue;
   } 

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMovimientos = new javax.swing.JLabel();
        jLabelMovimientosText = new javax.swing.JLabel();
        jLabelReportes = new javax.swing.JLabel();
        jLabelCuentas = new javax.swing.JLabel();
        jLabelInformacion = new javax.swing.JLabel();
        jLabelReportesText = new javax.swing.JLabel();
        jLabelCuentasText = new javax.swing.JLabel();
        jLabelInformacionText = new javax.swing.JLabel();
        jLabelIngresos = new javax.swing.JLabel();
        jLabelEgresos = new javax.swing.JLabel();
        jLabelEgresosText = new javax.swing.JLabel();
        jLabelIngresosText = new javax.swing.JLabel();
        jLabelCerrarSesion = new javax.swing.JLabel();
        jLabelCerrarSesionText = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MovimientosAzul.png"))); // NOI18N
        jLabelMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMovimientosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMovimientosMouseExited(evt);
            }
        });
        getContentPane().add(jLabelMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jLabelMovimientosText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelMovimientosText.setText("Movimientos");
        jLabelMovimientosText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMovimientosTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMovimientosTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelMovimientosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabelReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReportesBlanco.png"))); // NOI18N
        jLabelReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelReportesMouseExited(evt);
            }
        });
        getContentPane().add(jLabelReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jLabelCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuentasBlanco.png"))); // NOI18N
        jLabelCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCuentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCuentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCuentasMouseExited(evt);
            }
        });
        getContentPane().add(jLabelCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialBlanco.png"))); // NOI18N
        jLabelInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInformacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelInformacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelInformacionMouseExited(evt);
            }
        });
        getContentPane().add(jLabelInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        jLabelReportesText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelReportesText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReportesText.setText("Reportes");
        jLabelReportesText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelReportesTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelReportesTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelReportesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabelCuentasText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelCuentasText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCuentasText.setText("Cuentas");
        jLabelCuentasText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCuentasTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCuentasTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCuentasTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelCuentasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jLabelInformacionText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelInformacionText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInformacionText.setText("Tutorial");
        jLabelInformacionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInformacionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelInformacionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelInformacionTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelInformacionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, -1));

        jLabelIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingresos.png"))); // NOI18N
        jLabelIngresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIngresosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIngresosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIngresosMouseExited(evt);
            }
        });
        getContentPane().add(jLabelIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, -1, -1));

        jLabelEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Egresos.png"))); // NOI18N
        jLabelEgresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEgresosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEgresosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEgresosMouseExited(evt);
            }
        });
        getContentPane().add(jLabelEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, -1, -1));

        jLabelEgresosText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelEgresosText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEgresosText.setText("Añadir Egresos");
        jLabelEgresosText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEgresosTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEgresosTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEgresosTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelEgresosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, -1, -1));

        jLabelIngresosText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelIngresosText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngresosText.setText("Añadir Ingresos");
        jLabelIngresosText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIngresosTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIngresosTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIngresosTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelIngresosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, -1, -1));

        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeBlanco.png"))); // NOI18N
        jLabelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseExited(evt);
            }
        });
        getContentPane().add(jLabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));

        jLabelCerrarSesionText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelCerrarSesionText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrarSesionText.setText("Cerrar Sesión");
        jLabelCerrarSesionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelCerrarSesionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, -1, -1));

        jLabelFondo.setForeground(new java.awt.Color(0, 0, 102));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu1.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMovimientosTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosTextMouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jLabelMovimientosTextMouseEntered

    private void jLabelMovimientosTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosTextMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabelMovimientosTextMouseExited

    private void jLabelReportesTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReportesTextMouseEntered
        // TODO add your handling code here:
        jLabelReportesText.setForeground(Color.BLACK);
        jLabelReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReportesAzul.png")));
    }//GEN-LAST:event_jLabelReportesTextMouseEntered

    private void jLabelReportesTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReportesTextMouseExited
        // TODO add your handling code here:
        jLabelReportesText.setForeground(Color.WHITE);
        jLabelReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReportesBlanco.png")));
    }//GEN-LAST:event_jLabelReportesTextMouseExited

    private void jLabelInformacionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionTextMouseEntered
        // TODO add your handling code here:
                jLabelInformacionText.setForeground(Color.BLACK);
                jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialAzul.png")));

    }//GEN-LAST:event_jLabelInformacionTextMouseEntered

    private void jLabelInformacionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionTextMouseExited
        // TODO add your handling code here:
        jLabelInformacionText.setForeground(Color.WHITE);
         jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialBlanco.png")));
    }//GEN-LAST:event_jLabelInformacionTextMouseExited

    private void jLabelEgresosTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEgresosTextMouseEntered
        // TODO add your handling code here:
        jLabelEgresosText.setForeground(Color.BLACK);
       
    }//GEN-LAST:event_jLabelEgresosTextMouseEntered

    private void jLabelEgresosTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEgresosTextMouseExited
        // TODO add your handling code here:
        jLabelEgresosText.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_jLabelEgresosTextMouseExited

    private void jLabelIngresosTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresosTextMouseEntered
        // TODO add your handling code here:
        jLabelIngresosText.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_jLabelIngresosTextMouseEntered

    private void jLabelIngresosTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresosTextMouseExited
        // TODO add your handling code here:
        jLabelIngresosText.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_jLabelIngresosTextMouseExited

    private void jLabelCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseClicked
        // TODO add your handling code here:
         new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCerrarSesionMouseClicked

    private void jLabelCerrarSesionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionTextMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCerrarSesionTextMouseClicked

    private void jLabelCerrarSesionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionTextMouseEntered
        // TODO add your handling code here:
        jLabelCerrarSesionText.setForeground(Color.BLACK);
        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeAzul.png")));
        
    }//GEN-LAST:event_jLabelCerrarSesionTextMouseEntered

    private void jLabelCerrarSesionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionTextMouseExited
        // TODO add your handling code here:
        jLabelCerrarSesionText.setForeground(Color.WHITE);
        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeBlanco.png")));
    }//GEN-LAST:event_jLabelCerrarSesionTextMouseExited

    private void jLabelMovimientosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosMouseEntered
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLabelMovimientosMouseEntered

    private void jLabelMovimientosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabelMovimientosMouseExited

    private void jLabelReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReportesMouseEntered
        // TODO add your handling code here:
        jLabelReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReportesAzul.png")));
         jLabelReportesText.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelReportesMouseEntered

    private void jLabelReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReportesMouseExited
        // TODO add your handling code here:
        jLabelReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReportesBlanco.png")));
        jLabelReportesText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelReportesMouseExited

    private void jLabelInformacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionMouseEntered
        // TODO add your handling code here:
        jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialAzul.png")));
        jLabelInformacionText.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelInformacionMouseEntered

    private void jLabelInformacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionMouseExited
        // TODO add your handling code here:
        jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialBlanco.png")));
        jLabelInformacionText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelInformacionMouseExited

    private void jLabelCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseEntered
        // TODO add your handling code here:
        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeAzul.png")));
        jLabelCerrarSesionText.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_jLabelCerrarSesionMouseEntered

    private void jLabelCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseExited
        // TODO add your handling code here:
        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeBlanco.png")));
        jLabelCerrarSesionText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelCerrarSesionMouseExited

    private void jLabelIngresosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresosMouseEntered
        // TODO add your handling code here:
        
        jLabelIngresosText.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelIngresosMouseEntered

    private void jLabelIngresosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresosMouseExited
        // TODO add your handling code here:
        
         jLabelIngresosText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelIngresosMouseExited

    private void jLabelInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionMouseClicked
        // TODO add your handling code here:
        new Tutorial1(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelInformacionMouseClicked

    private void jLabelInformacionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionTextMouseClicked
        // TODO add your handling code here:
        new Tutorial1(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelInformacionTextMouseClicked

    private void jLabelIngresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresosMouseClicked
        // TODO add your handling code here:
        new AñadirIngresos().setVisible(true);
        
    }//GEN-LAST:event_jLabelIngresosMouseClicked

    private void jLabelIngresosTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresosTextMouseClicked
        // TODO add your handling code here:
        new AñadirIngresos().setVisible(true);
    }//GEN-LAST:event_jLabelIngresosTextMouseClicked

    private void jLabelEgresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEgresosMouseClicked
        // TODO add your handling code here:
        new AñadirEgresos().setVisible(true);
    }//GEN-LAST:event_jLabelEgresosMouseClicked

    private void jLabelEgresosTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEgresosTextMouseClicked
        // TODO add your handling code here:
        new AñadirEgresos().setVisible(true);
    }//GEN-LAST:event_jLabelEgresosTextMouseClicked

    private void jLabelCuentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCuentasMouseEntered
        // TODO add your handling code here:
        jLabelCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuentasAzul.png")));
        jLabelCuentasText.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelCuentasMouseEntered

    private void jLabelCuentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCuentasMouseExited
        // TODO add your handling code here:
        jLabelCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuentasBlanco.png")));
        jLabelCuentasText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelCuentasMouseExited

    private void jLabelCuentasTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCuentasTextMouseEntered
        // TODO add your handling code here:
        jLabelCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuentasAzul.png")));
        jLabelCuentasText.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelCuentasTextMouseEntered

    private void jLabelCuentasTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCuentasTextMouseExited
        // TODO add your handling code here:
        jLabelCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuentasBlanco.png")));
        jLabelCuentasText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelCuentasTextMouseExited

    private void jLabelCuentasTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCuentasTextMouseClicked
        // TODO add your handling code here:
         new MenuCuentas(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCuentasTextMouseClicked

    private void jLabelCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCuentasMouseClicked
        // TODO add your handling code here:
         new MenuCuentas(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCuentasMouseClicked

    private void jLabelEgresosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEgresosMouseEntered
        // TODO add your handling code here:
         jLabelEgresosText.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelEgresosMouseEntered

    private void jLabelEgresosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEgresosMouseExited
        // TODO add your handling code here:
         jLabelEgresosText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelEgresosMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCerrarSesion;
    private javax.swing.JLabel jLabelCerrarSesionText;
    private javax.swing.JLabel jLabelCuentas;
    private javax.swing.JLabel jLabelCuentasText;
    private javax.swing.JLabel jLabelEgresos;
    private javax.swing.JLabel jLabelEgresosText;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInformacion;
    private javax.swing.JLabel jLabelInformacionText;
    private javax.swing.JLabel jLabelIngresos;
    private javax.swing.JLabel jLabelIngresosText;
    private javax.swing.JLabel jLabelMovimientos;
    private javax.swing.JLabel jLabelMovimientosText;
    private javax.swing.JLabel jLabelReportes;
    private javax.swing.JLabel jLabelReportesText;
    // End of variables declaration//GEN-END:variables
}
