/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import entidades.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Frognas
 */
public class MenuCuentas extends javax.swing.JFrame {
    
    private Usuario user;
    /**
     * Creates new form MenuCuentas
     * @param user
     */
    public MenuCuentas(Usuario user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
    }

     public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo2.png"));
       return retValue;
   } 
 
        
        /*
        String headers[] = {"Username","Password","Name"};
        String data[][] = getData();
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem editUserItem = new JMenuItem("Edit user");
        JMenuItem deleteUserItem = new JMenuItem("Delete user");
        popupMenu.add(editUserItem);
        popupMenu.add(deleteUserItem);
           
        DefaultTableModel model = new DefaultTableModel(data, headers);
        tbUsers.setModel(model);
        tbUsers.setComponentPopupMenu(popupMenu);
        tbUsers.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                Point point = e.getPoint();
                int currentRow = tbUsers.rowAtPoint(point);
                tbUsers.setRowSelectionInterval(currentRow, currentRow);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        
        editUserItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            }
        });
        deleteUserItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedRow = tbUsers.getSelectedRow();
                try{
                    if(userDao.deleteUser(users.get(selectedRow).getUsername())){
                        model.removeRow(selectedRow);
                    }else{
                        JOptionPane.showMessageDialog(me, "Something is worng, please try again","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }catch(SQLException ex){
                    System.out.println("Error: " + ex.getMessage());
                }
            }
        });
        editUserItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedRow = tbUsers.getSelectedRow();
                
                EditUser editUser = new EditUser(me,users.get(selectedRow),model,selectedRow);
                me.setVisible(false);
                editUser.setVisible(true);
                
            }
        });
    }
 */
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMovimientos = new javax.swing.JLabel();
        jLabelMovimientosText = new javax.swing.JLabel();
        jLabelCuentas = new javax.swing.JLabel();
        jLabelInformacion = new javax.swing.JLabel();
        jLabelCuentasText = new javax.swing.JLabel();
        jLabelInformacionText = new javax.swing.JLabel();
        jLabelAñadirCuenta = new javax.swing.JLabel();
        jLabelTransferencia = new javax.swing.JLabel();
        jLabelTransferenciaText = new javax.swing.JLabel();
        jLabelAñadirCuentaText = new javax.swing.JLabel();
        jLabelCerrarSesion = new javax.swing.JLabel();
        jLabelCerrarSesionText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MovimientosBlanco.png"))); // NOI18N
        jLabelMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMovimientosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMovimientosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMovimientosMouseExited(evt);
            }
        });
        getContentPane().add(jLabelMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabelMovimientosText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelMovimientosText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMovimientosText.setText("Movimientos");
        jLabelMovimientosText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMovimientosTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMovimientosTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMovimientosTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelMovimientosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabelCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuentasAzul.png"))); // NOI18N
        getContentPane().add(jLabelCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialBlanco.png"))); // NOI18N
        jLabelInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInformacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelInformacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelInformacionMouseExited(evt);
            }
        });
        getContentPane().add(jLabelInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        jLabelCuentasText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelCuentasText.setText("Cuentas");
        getContentPane().add(jLabelCuentasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jLabelInformacionText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelInformacionText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInformacionText.setText("Tutorial");
        jLabelInformacionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInformacionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelInformacionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelInformacionTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelInformacionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, -1));

        jLabelAñadirCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirCuentaBlanco.png"))); // NOI18N
        jLabelAñadirCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAñadirCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAñadirCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAñadirCuentaMouseExited(evt);
            }
        });
        getContentPane().add(jLabelAñadirCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, -1, -1));

        jLabelTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirTransferenciaBlanco.png"))); // NOI18N
        jLabelTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTransferenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTransferenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTransferenciaMouseExited(evt);
            }
        });
        getContentPane().add(jLabelTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, -1, -1));

        jLabelTransferenciaText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelTransferenciaText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTransferenciaText.setText("Añadir Transferencia");
        jLabelTransferenciaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTransferenciaTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTransferenciaTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTransferenciaTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelTransferenciaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));

        jLabelAñadirCuentaText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelAñadirCuentaText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAñadirCuentaText.setText("Añadir Cuenta");
        jLabelAñadirCuentaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAñadirCuentaTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAñadirCuentaTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAñadirCuentaTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelAñadirCuentaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, -1, -1));

        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeBlanco.png"))); // NOI18N
        jLabelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseExited(evt);
            }
        });
        getContentPane().add(jLabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));

        jLabelCerrarSesionText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelCerrarSesionText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrarSesionText.setText("Cerrar Sesión");
        jLabelCerrarSesionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionTextMouseExited(evt);
            }
        });
        getContentPane().add(jLabelCerrarSesionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 1030, 370));

        jLabelFondo.setForeground(new java.awt.Color(0, 0, 102));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu1.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMovimientosTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosTextMouseEntered
        // TODO add your handling code here:
        jLabelMovimientosText.setForeground(Color.BLACK);
        jLabelMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MovimientosAzul.png")));
    }//GEN-LAST:event_jLabelMovimientosTextMouseEntered

    private void jLabelMovimientosTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosTextMouseExited
        // TODO add your handling code here:
        jLabelMovimientosText.setForeground(Color.WHITE);
        jLabelMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MovimientosBlanco.png")));
    }//GEN-LAST:event_jLabelMovimientosTextMouseExited

    private void jLabelInformacionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionTextMouseEntered
        // TODO add your handling code here:
                jLabelInformacionText.setForeground(Color.BLACK);
                jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialAzul.png")));

    }//GEN-LAST:event_jLabelInformacionTextMouseEntered

    private void jLabelInformacionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionTextMouseExited
        // TODO add your handling code here:
        jLabelInformacionText.setForeground(Color.WHITE);
         jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialBlanco.png")));
    }//GEN-LAST:event_jLabelInformacionTextMouseExited

    private void jLabelTransferenciaTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransferenciaTextMouseEntered
        // TODO add your handling code here:
        jLabelTransferenciaText.setForeground(Color.BLACK);
        jLabelTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirTransferenciaAzul.png")));
    }//GEN-LAST:event_jLabelTransferenciaTextMouseEntered

    private void jLabelTransferenciaTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransferenciaTextMouseExited
        // TODO add your handling code here:
        jLabelTransferenciaText.setForeground(Color.WHITE);
        jLabelTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirTransferenciaBlanco.png")));
    }//GEN-LAST:event_jLabelTransferenciaTextMouseExited

    private void jLabelAñadirCuentaTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAñadirCuentaTextMouseEntered
        // TODO add your handling code here:
        jLabelAñadirCuentaText.setForeground(Color.BLACK);
        jLabelAñadirCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirCuentaAzul.png")));
    }//GEN-LAST:event_jLabelAñadirCuentaTextMouseEntered

    private void jLabelAñadirCuentaTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAñadirCuentaTextMouseExited
        // TODO add your handling code here:
        jLabelAñadirCuentaText.setForeground(Color.WHITE);
        jLabelAñadirCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirCuentaBlanco.png")));
    }//GEN-LAST:event_jLabelAñadirCuentaTextMouseExited

    private void jLabelMovimientosTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosTextMouseClicked
        // TODO add your handling code here:
        new MenuMovimientos(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelMovimientosTextMouseClicked

    private void jLabelMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosMouseClicked
        // TODO add your handling code here:
        new MenuMovimientos(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelMovimientosMouseClicked

    private void jLabelCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCerrarSesionMouseClicked

    private void jLabelCerrarSesionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionTextMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCerrarSesionTextMouseClicked

    private void jLabelCerrarSesionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionTextMouseEntered
        // TODO add your handling code here:
        jLabelCerrarSesionText.setForeground(Color.BLACK);
        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeAzul.png")));
        
    }//GEN-LAST:event_jLabelCerrarSesionTextMouseEntered

    private void jLabelCerrarSesionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionTextMouseExited
        // TODO add your handling code here:
        jLabelCerrarSesionText.setForeground(Color.WHITE);
        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeBlanco.png")));
    }//GEN-LAST:event_jLabelCerrarSesionTextMouseExited

    private void jLabelMovimientosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosMouseEntered
        // TODO add your handling code here:
        jLabelMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MovimientosAzul.png")));
         jLabelMovimientosText.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_jLabelMovimientosMouseEntered

    private void jLabelMovimientosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMovimientosMouseExited
        // TODO add your handling code here:
        jLabelMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MovimientosBlanco.png")));
        jLabelMovimientosText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelMovimientosMouseExited

    private void jLabelInformacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionMouseEntered
        // TODO add your handling code here:
        jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialAzul.png")));
        jLabelInformacionText.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelInformacionMouseEntered

    private void jLabelInformacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionMouseExited
        // TODO add your handling code here:
        jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TutorialBlanco.png")));
        jLabelInformacionText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelInformacionMouseExited

    private void jLabelCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseEntered
        // TODO add your handling code here:
        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeAzul.png")));
        jLabelCerrarSesionText.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_jLabelCerrarSesionMouseEntered

    private void jLabelCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseExited
        // TODO add your handling code here:
        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EngranajeBlanco.png")));
        jLabelCerrarSesionText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelCerrarSesionMouseExited

    private void jLabelTransferenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransferenciaMouseEntered
        // TODO add your handling code here:
        jLabelTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirTransferenciaAzul.png")));
        jLabelTransferenciaText.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_jLabelTransferenciaMouseEntered

    private void jLabelTransferenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransferenciaMouseExited
        // TODO add your handling code here:
        jLabelTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirTransferenciaBlanco.png")));
        jLabelTransferenciaText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelTransferenciaMouseExited

    private void jLabelAñadirCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAñadirCuentaMouseEntered
        // TODO add your handling code here:
        jLabelAñadirCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirCuentaAzul.png")));
        jLabelAñadirCuentaText.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelAñadirCuentaMouseEntered

    private void jLabelAñadirCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAñadirCuentaMouseExited
        // TODO add your handling code here:
         jLabelAñadirCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirCuentaBlanco.png")));
         jLabelAñadirCuentaText.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelAñadirCuentaMouseExited

    private void jLabelInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionMouseClicked
        // TODO add your handling code here:
        new Tutorial1(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelInformacionMouseClicked

    private void jLabelInformacionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformacionTextMouseClicked
        // TODO add your handling code here:
        new Tutorial1(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelInformacionTextMouseClicked

    private void jLabelAñadirCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAñadirCuentaMouseClicked
        // TODO add your handling code here:
        new AñadirCuenta().setVisible(true);
        
    }//GEN-LAST:event_jLabelAñadirCuentaMouseClicked

    private void jLabelAñadirCuentaTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAñadirCuentaTextMouseClicked
        // TODO add your handling code here:
        new AñadirCuenta().setVisible(true);
    }//GEN-LAST:event_jLabelAñadirCuentaTextMouseClicked

    private void jLabelTransferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransferenciaMouseClicked
        // TODO add your handling code here:
        new AñadirTransferencia().setVisible(true);
    }//GEN-LAST:event_jLabelTransferenciaMouseClicked

    private void jLabelTransferenciaTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransferenciaTextMouseClicked
        // TODO add your handling code here:
        new AñadirTransferencia().setVisible(true);
    }//GEN-LAST:event_jLabelTransferenciaTextMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAñadirCuenta;
    private javax.swing.JLabel jLabelAñadirCuentaText;
    private javax.swing.JLabel jLabelCerrarSesion;
    private javax.swing.JLabel jLabelCerrarSesionText;
    private javax.swing.JLabel jLabelCuentas;
    private javax.swing.JLabel jLabelCuentasText;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInformacion;
    private javax.swing.JLabel jLabelInformacionText;
    private javax.swing.JLabel jLabelMovimientos;
    private javax.swing.JLabel jLabelMovimientosText;
    private javax.swing.JLabel jLabelTransferencia;
    private javax.swing.JLabel jLabelTransferenciaText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
