/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import sql.DBQuery;

/**
 *
 * @author Frognas
 */
public class RestablecerContraseña extends javax.swing.JFrame {

    private DBQuery query;
    /**
     * Creates new form SignIn
     */
    public RestablecerContraseña() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabelIncorrecto.setVisible(false);
        query = new DBQuery();
    }

    
    public void limpiarCampos(){
        jTextUsuario.setText("");
        jTextContraseña.setText("");
        jTextContraseña2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegresar = new javax.swing.JLabel();
        jLabelRestablecer = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jTextContraseña = new javax.swing.JPasswordField();
        jTextContraseña2 = new javax.swing.JPasswordField();
        jLabelBuscar = new javax.swing.JLabel();
        jLabelIncorrecto = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 200, 80));

        jLabelRestablecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Restablecer.png"))); // NOI18N
        jLabelRestablecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRestablecerMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 470, 200, 80));

        jTextUsuario.setBackground(new java.awt.Color(0, 28, 75));
        jTextUsuario.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextUsuario.setBorder(null);
        getContentPane().add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 320, 30));

        jTextContraseña.setBackground(new java.awt.Color(0, 28, 75));
        jTextContraseña.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jTextContraseña.setBorder(null);
        getContentPane().add(jTextContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 340, 30));

        jTextContraseña2.setBackground(new java.awt.Color(0, 28, 75));
        jTextContraseña2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextContraseña2.setForeground(new java.awt.Color(255, 255, 255));
        jTextContraseña2.setBorder(null);
        getContentPane().add(jTextContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 340, 30));

        jLabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jLabelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 140, 100, 50));

        jLabelIncorrecto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelIncorrecto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIncorrecto.setText("¡Usuario no encontrado o contraseñas no coinciden!");
        getContentPane().add(jLabelIncorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RestablecerContraseña.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelRegresarMouseClicked

    private void jLabelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarMouseClicked
        // TODO add your handling code here:
        String user = jTextUsuario.getText();
        String usuario = query.findUser(user);
        if (usuario != null) {
            jTextUsuario.setEnabled(false);
            jLabelBuscar.setEnabled(false);
            jLabelIncorrecto.setVisible(false);
            JOptionPane.showMessageDialog(this, "Usuario encontrado", "Succes", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jLabelIncorrecto.setVisible(true);
        }
    }//GEN-LAST:event_jLabelBuscarMouseClicked

    private void jLabelRestablecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRestablecerMouseClicked
        // TODO add your handling code here:
        if (jTextContraseña.getPassword().equals("") || jTextContraseña2.getPassword().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos no pueden estar vacios.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try{

                if (query.updatePass(jTextUsuario.getText(), new String(jTextContraseña.getPassword())) 
                        && new String(jTextContraseña.getPassword()).equals(new String(jTextContraseña2.getPassword()))) {
                    JOptionPane.showMessageDialog(this,"User edited successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                } else {
                    jLabelIncorrecto.setVisible(true);
                }
            } catch (SQLException se){
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabelRestablecerMouseClicked

    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo2.png"));
       return retValue;
   } 
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestablecerContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIncorrecto;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelRestablecer;
    private javax.swing.JPasswordField jTextContraseña;
    private javax.swing.JPasswordField jTextContraseña2;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
