/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import entidades.Usuario;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Frognas
 */
public class Tutorial3 extends javax.swing.JFrame {

    private Usuario user;
    /**
     * Creates new form Tutorial1
     * @param user
     */
    public Tutorial3(Usuario user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo2.png"));
       return retValue;
   } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSiguiente = new javax.swing.JLabel();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonSiguiente.png"))); // NOI18N
        jLabelSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSiguienteMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, 200, 80));

        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonRegresar.png"))); // NOI18N
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 200, 80));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tutorial3.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMouseClicked
        // TODO add your handling code here:
        new Tutorial2(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelRegresarMouseClicked

    private void jLabelSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSiguienteMouseClicked
        // TODO add your handling code here:
        new Tutorial4(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelSiguienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelSiguiente;
    // End of variables declaration//GEN-END:variables
}
